### ISSUE TITLE
Dificil leitura do texto

### ISSUE THREAD

**Issue by IltonBJSilva** [Nerd0000/Nerd0000.github.io#1]
Ola tudo bem? bem legal a pagina que fez como seu curriculo top, so que tipo a cor do texto com o fundo acaba dificultando a leitura um pouco, e para melhorar o design recomendo usar bootstrap, caso nao saiba oque seja, e um framework que ajuda no design deixando a pagina mas atraente, mas bonita.

**Comment by Nerd0000** [comment]
Poxa, não conheço Bootstrap ainda, mas vou tentar colocar a cor mais para o lado do preto para facilitar a leitura ja que o texto está em branco.
>Obrigado pela dica

**Comment by Nerd0000** [comment]
@IltonBJSilva , melhorou?
